// Generated by Wrangler on Sat May 25 2024 23:07:29 GMT-0600 (Mountain Daylight Time)
// by running `wrangler types`

interface Env {
	SENDGRID_API_KEY: string;
	FROM_EMAIL: string;
	TO_EMAIL: string;
}
